// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loopholelabs/auth/pkg/storage/default/ent/predicate"
	"github.com/loopholelabs/auth/pkg/storage/default/ent/servicekey"
	"github.com/loopholelabs/auth/pkg/storage/default/ent/user"
)

// ServiceKeyQuery is the builder for querying ServiceKey entities.
type ServiceKeyQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ServiceKey
	withOwner  *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ServiceKeyQuery builder.
func (skq *ServiceKeyQuery) Where(ps ...predicate.ServiceKey) *ServiceKeyQuery {
	skq.predicates = append(skq.predicates, ps...)
	return skq
}

// Limit adds a limit step to the query.
func (skq *ServiceKeyQuery) Limit(limit int) *ServiceKeyQuery {
	skq.limit = &limit
	return skq
}

// Offset adds an offset step to the query.
func (skq *ServiceKeyQuery) Offset(offset int) *ServiceKeyQuery {
	skq.offset = &offset
	return skq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (skq *ServiceKeyQuery) Unique(unique bool) *ServiceKeyQuery {
	skq.unique = &unique
	return skq
}

// Order adds an order step to the query.
func (skq *ServiceKeyQuery) Order(o ...OrderFunc) *ServiceKeyQuery {
	skq.order = append(skq.order, o...)
	return skq
}

// QueryOwner chains the current query on the "owner" edge.
func (skq *ServiceKeyQuery) QueryOwner() *UserQuery {
	query := &UserQuery{config: skq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := skq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := skq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(servicekey.Table, servicekey.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, servicekey.OwnerTable, servicekey.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(skq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ServiceKey entity from the query.
// Returns a *NotFoundError when no ServiceKey was found.
func (skq *ServiceKeyQuery) First(ctx context.Context) (*ServiceKey, error) {
	nodes, err := skq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{servicekey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (skq *ServiceKeyQuery) FirstX(ctx context.Context) *ServiceKey {
	node, err := skq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ServiceKey ID from the query.
// Returns a *NotFoundError when no ServiceKey ID was found.
func (skq *ServiceKeyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = skq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{servicekey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (skq *ServiceKeyQuery) FirstIDX(ctx context.Context) int {
	id, err := skq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ServiceKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ServiceKey entity is found.
// Returns a *NotFoundError when no ServiceKey entities are found.
func (skq *ServiceKeyQuery) Only(ctx context.Context) (*ServiceKey, error) {
	nodes, err := skq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{servicekey.Label}
	default:
		return nil, &NotSingularError{servicekey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (skq *ServiceKeyQuery) OnlyX(ctx context.Context) *ServiceKey {
	node, err := skq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ServiceKey ID in the query.
// Returns a *NotSingularError when more than one ServiceKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (skq *ServiceKeyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = skq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{servicekey.Label}
	default:
		err = &NotSingularError{servicekey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (skq *ServiceKeyQuery) OnlyIDX(ctx context.Context) int {
	id, err := skq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ServiceKeys.
func (skq *ServiceKeyQuery) All(ctx context.Context) ([]*ServiceKey, error) {
	if err := skq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return skq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (skq *ServiceKeyQuery) AllX(ctx context.Context) []*ServiceKey {
	nodes, err := skq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ServiceKey IDs.
func (skq *ServiceKeyQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := skq.Select(servicekey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (skq *ServiceKeyQuery) IDsX(ctx context.Context) []int {
	ids, err := skq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (skq *ServiceKeyQuery) Count(ctx context.Context) (int, error) {
	if err := skq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return skq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (skq *ServiceKeyQuery) CountX(ctx context.Context) int {
	count, err := skq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (skq *ServiceKeyQuery) Exist(ctx context.Context) (bool, error) {
	if err := skq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return skq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (skq *ServiceKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := skq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ServiceKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (skq *ServiceKeyQuery) Clone() *ServiceKeyQuery {
	if skq == nil {
		return nil
	}
	return &ServiceKeyQuery{
		config:     skq.config,
		limit:      skq.limit,
		offset:     skq.offset,
		order:      append([]OrderFunc{}, skq.order...),
		predicates: append([]predicate.ServiceKey{}, skq.predicates...),
		withOwner:  skq.withOwner.Clone(),
		// clone intermediate query.
		sql:    skq.sql.Clone(),
		path:   skq.path,
		unique: skq.unique,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (skq *ServiceKeyQuery) WithOwner(opts ...func(*UserQuery)) *ServiceKeyQuery {
	query := &UserQuery{config: skq.config}
	for _, opt := range opts {
		opt(query)
	}
	skq.withOwner = query
	return skq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ServiceKey.Query().
//		GroupBy(servicekey.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (skq *ServiceKeyQuery) GroupBy(field string, fields ...string) *ServiceKeyGroupBy {
	grbuild := &ServiceKeyGroupBy{config: skq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := skq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return skq.sqlQuery(ctx), nil
	}
	grbuild.label = servicekey.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt int64 `json:"created_at,omitempty"`
//	}
//
//	client.ServiceKey.Query().
//		Select(servicekey.FieldCreatedAt).
//		Scan(ctx, &v)
func (skq *ServiceKeyQuery) Select(fields ...string) *ServiceKeySelect {
	skq.fields = append(skq.fields, fields...)
	selbuild := &ServiceKeySelect{ServiceKeyQuery: skq}
	selbuild.label = servicekey.Label
	selbuild.flds, selbuild.scan = &skq.fields, selbuild.Scan
	return selbuild
}

func (skq *ServiceKeyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range skq.fields {
		if !servicekey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if skq.path != nil {
		prev, err := skq.path(ctx)
		if err != nil {
			return err
		}
		skq.sql = prev
	}
	return nil
}

func (skq *ServiceKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ServiceKey, error) {
	var (
		nodes       = []*ServiceKey{}
		withFKs     = skq.withFKs
		_spec       = skq.querySpec()
		loadedTypes = [1]bool{
			skq.withOwner != nil,
		}
	)
	if skq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, servicekey.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ServiceKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ServiceKey{config: skq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, skq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := skq.withOwner; query != nil {
		if err := skq.loadOwner(ctx, query, nodes, nil,
			func(n *ServiceKey, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (skq *ServiceKeyQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*ServiceKey, init func(*ServiceKey), assign func(*ServiceKey, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ServiceKey)
	for i := range nodes {
		if nodes[i].user_servicekeys == nil {
			continue
		}
		fk := *nodes[i].user_servicekeys
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_servicekeys" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (skq *ServiceKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := skq.querySpec()
	_spec.Node.Columns = skq.fields
	if len(skq.fields) > 0 {
		_spec.Unique = skq.unique != nil && *skq.unique
	}
	return sqlgraph.CountNodes(ctx, skq.driver, _spec)
}

func (skq *ServiceKeyQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := skq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (skq *ServiceKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   servicekey.Table,
			Columns: servicekey.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: servicekey.FieldID,
			},
		},
		From:   skq.sql,
		Unique: true,
	}
	if unique := skq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := skq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, servicekey.FieldID)
		for i := range fields {
			if fields[i] != servicekey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := skq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := skq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := skq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := skq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (skq *ServiceKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(skq.driver.Dialect())
	t1 := builder.Table(servicekey.Table)
	columns := skq.fields
	if len(columns) == 0 {
		columns = servicekey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if skq.sql != nil {
		selector = skq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if skq.unique != nil && *skq.unique {
		selector.Distinct()
	}
	for _, p := range skq.predicates {
		p(selector)
	}
	for _, p := range skq.order {
		p(selector)
	}
	if offset := skq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := skq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ServiceKeyGroupBy is the group-by builder for ServiceKey entities.
type ServiceKeyGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (skgb *ServiceKeyGroupBy) Aggregate(fns ...AggregateFunc) *ServiceKeyGroupBy {
	skgb.fns = append(skgb.fns, fns...)
	return skgb
}

// Scan applies the group-by query and scans the result into the given value.
func (skgb *ServiceKeyGroupBy) Scan(ctx context.Context, v any) error {
	query, err := skgb.path(ctx)
	if err != nil {
		return err
	}
	skgb.sql = query
	return skgb.sqlScan(ctx, v)
}

func (skgb *ServiceKeyGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range skgb.fields {
		if !servicekey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := skgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := skgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (skgb *ServiceKeyGroupBy) sqlQuery() *sql.Selector {
	selector := skgb.sql.Select()
	aggregation := make([]string, 0, len(skgb.fns))
	for _, fn := range skgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(skgb.fields)+len(skgb.fns))
		for _, f := range skgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(skgb.fields...)...)
}

// ServiceKeySelect is the builder for selecting fields of ServiceKey entities.
type ServiceKeySelect struct {
	*ServiceKeyQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (sks *ServiceKeySelect) Scan(ctx context.Context, v any) error {
	if err := sks.prepareQuery(ctx); err != nil {
		return err
	}
	sks.sql = sks.ServiceKeyQuery.sqlQuery(ctx)
	return sks.sqlScan(ctx, v)
}

func (sks *ServiceKeySelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := sks.sql.Query()
	if err := sks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
