/*
	Copyright 2023 Loophole Labs

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		   http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loopholelabs/auth/internal/ent/googleflow"
	"github.com/loopholelabs/auth/internal/ent/predicate"
)

// GoogleFlowDelete is the builder for deleting a GoogleFlow entity.
type GoogleFlowDelete struct {
	config
	hooks    []Hook
	mutation *GoogleFlowMutation
}

// Where appends a list predicates to the GoogleFlowDelete builder.
func (gfd *GoogleFlowDelete) Where(ps ...predicate.GoogleFlow) *GoogleFlowDelete {
	gfd.mutation.Where(ps...)
	return gfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gfd *GoogleFlowDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, gfd.sqlExec, gfd.mutation, gfd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gfd *GoogleFlowDelete) ExecX(ctx context.Context) int {
	n, err := gfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gfd *GoogleFlowDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(googleflow.Table, sqlgraph.NewFieldSpec(googleflow.FieldID, field.TypeInt))
	if ps := gfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gfd.mutation.done = true
	return affected, err
}

// GoogleFlowDeleteOne is the builder for deleting a single GoogleFlow entity.
type GoogleFlowDeleteOne struct {
	gfd *GoogleFlowDelete
}

// Where appends a list predicates to the GoogleFlowDelete builder.
func (gfdo *GoogleFlowDeleteOne) Where(ps ...predicate.GoogleFlow) *GoogleFlowDeleteOne {
	gfdo.gfd.mutation.Where(ps...)
	return gfdo
}

// Exec executes the deletion query.
func (gfdo *GoogleFlowDeleteOne) Exec(ctx context.Context) error {
	n, err := gfdo.gfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{googleflow.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gfdo *GoogleFlowDeleteOne) ExecX(ctx context.Context) {
	if err := gfdo.Exec(ctx); err != nil {
		panic(err)
	}
}
