// Code generated by go-swagger; DO NOT EDIT.

package servicekey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostServicekeyLoginParams creates a new PostServicekeyLoginParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostServicekeyLoginParams() *PostServicekeyLoginParams {
	return &PostServicekeyLoginParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostServicekeyLoginParamsWithTimeout creates a new PostServicekeyLoginParams object
// with the ability to set a timeout on a request.
func NewPostServicekeyLoginParamsWithTimeout(timeout time.Duration) *PostServicekeyLoginParams {
	return &PostServicekeyLoginParams{
		timeout: timeout,
	}
}

// NewPostServicekeyLoginParamsWithContext creates a new PostServicekeyLoginParams object
// with the ability to set a context for a request.
func NewPostServicekeyLoginParamsWithContext(ctx context.Context) *PostServicekeyLoginParams {
	return &PostServicekeyLoginParams{
		Context: ctx,
	}
}

// NewPostServicekeyLoginParamsWithHTTPClient creates a new PostServicekeyLoginParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostServicekeyLoginParamsWithHTTPClient(client *http.Client) *PostServicekeyLoginParams {
	return &PostServicekeyLoginParams{
		HTTPClient: client,
	}
}

/*
PostServicekeyLoginParams contains all the parameters to send to the API endpoint

	for the post servicekey login operation.

	Typically these are written to a http.Request.
*/
type PostServicekeyLoginParams struct {

	/* Servicekey.

	   Service Key
	*/
	Servicekey string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post servicekey login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostServicekeyLoginParams) WithDefaults() *PostServicekeyLoginParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post servicekey login params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostServicekeyLoginParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post servicekey login params
func (o *PostServicekeyLoginParams) WithTimeout(timeout time.Duration) *PostServicekeyLoginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post servicekey login params
func (o *PostServicekeyLoginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post servicekey login params
func (o *PostServicekeyLoginParams) WithContext(ctx context.Context) *PostServicekeyLoginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post servicekey login params
func (o *PostServicekeyLoginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post servicekey login params
func (o *PostServicekeyLoginParams) WithHTTPClient(client *http.Client) *PostServicekeyLoginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post servicekey login params
func (o *PostServicekeyLoginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithServicekey adds the servicekey to the post servicekey login params
func (o *PostServicekeyLoginParams) WithServicekey(servicekey string) *PostServicekeyLoginParams {
	o.SetServicekey(servicekey)
	return o
}

// SetServicekey adds the servicekey to the post servicekey login params
func (o *PostServicekeyLoginParams) SetServicekey(servicekey string) {
	o.Servicekey = servicekey
}

// WriteToRequest writes these params to a swagger request
func (o *PostServicekeyLoginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param servicekey
	qrServicekey := o.Servicekey
	qServicekey := qrServicekey
	if qServicekey != "" {

		if err := r.SetQueryParam("servicekey", qServicekey); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
