components:
  schemas:
    models.DeviceFlowResponse:
      properties:
        code:
          type: string
        poll:
          type: string
        polling_rate_seconds:
          type: integer
      type: object
    models.PublicResponse:
      properties:
        invalidated_sessions:
          items:
            $ref: '#/components/schemas/validator.InvalidatedSession'
          type: array
          uniqueItems: false
        previous_public_key:
          type: string
        public_key:
          type: string
        revoked_sessions:
          items:
            type: string
          type: array
          uniqueItems: false
      type: object
    validator.InvalidatedSession:
      properties:
        generation:
          type: integer
        identifier:
          type: string
      type: object
  securitySchemes:
    "":
      description: User Session Cookie
      in: cookie
      name: authentication_session
      type: apiKey
externalDocs:
  description: ""
  url: ""
info:
  contact:
    email: admin@loopholelabs.io
    name: API Support
  description: health returns the health check status
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://loopholelabs.io/privacy
  title: Auth API v1
  version: "1.0"
openapi: 3.1.0
paths:
  /flows/device/login:
    get:
      description: login logs in a user with the Device Code Flow
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.DeviceFlowResponse'
          description: OK
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: login logs in a user with the Device Code Flow
      tags:
      - device
      - login
  /flows/device/poll:
    get:
      description: poll polls the device code flow using the poll code
      parameters:
      - description: poll
        in: query
        name: poll
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
          headers:
            Set-Cookie:
              description: authentication_session=jwt_token; HttpOnly; SameSite=lax;
              schema:
                type: string
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                type: string
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                type: string
          description: Not Found
        "429":
          content:
            application/json:
              schema:
                type: string
          description: Too Many Requests
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: poll polls the device code flow using the poll code
      tags:
      - device
      - poll
  /flows/device/validate:
    get:
      description: validate validates the code
      parameters:
      - description: code
        in: query
        name: code
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                type: string
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: validate validates the code
      tags:
      - device
      - validate
  /flows/github/callback:
    get:
      description: callback logs in a user with Github
      parameters:
      - description: Next Redirect URL
        in: query
        name: code
        schema:
          type: string
      - description: Device Flow Code
        in: query
        name: state
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to Next URL
              schema:
                type: string
            Set-Cookie:
              description: authentication_session=jwt_token; HttpOnly; SameSite=lax;
              schema:
                type: string
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                type: string
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                type: string
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: callback logs in a user with Github
      tags:
      - github
      - callback
  /flows/github/info:
    get:
      description: info returns the information about a logged-in User
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to User
              schema:
                type: string
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                type: string
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: info returns the information about a logged-in User
      tags:
      - user
      - info
  /flows/github/login:
    get:
      description: login logs in a user with Github
      parameters:
      - description: Next Redirect URL
        in: query
        name: next
        required: true
        schema:
          type: string
      - description: Device Flow Code
        in: query
        name: code
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to Github
              schema:
                type: string
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                type: string
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: login logs in a user with Github
      tags:
      - github
      - login
  /flows/google/callback:
    get:
      description: callback logs in a user with Google
      parameters:
      - description: Next Redirect URL
        in: query
        name: code
        schema:
          type: string
      - description: Device Flow Code
        in: query
        name: state
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to Next URL
              schema:
                type: string
            Set-Cookie:
              description: authentication_session=jwt_token; HttpOnly; SameSite=lax;
              schema:
                type: string
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                type: string
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                type: string
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: callback logs in a user with Google
      tags:
      - google
      - callback
  /flows/google/login:
    get:
      description: login logs in a user with Google
      parameters:
      - description: Next Redirect URL
        in: query
        name: next
        required: true
        schema:
          type: string
      - description: Device Flow Code
        in: query
        name: code
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to Google
              schema:
                type: string
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                type: string
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: login logs in a user with Google
      tags:
      - google
      - login
  /flows/magic/callback:
    get:
      description: callback logs in a user with a Magic Link
      parameters:
      - description: magic link token
        in: query
        name: token
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to Next URL
              schema:
                type: string
            Set-Cookie:
              description: authentication_session=jwt_token; HttpOnly; SameSite=lax;
              schema:
                type: string
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                type: string
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                type: string
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: callback logs in a user with a Magic Link
      tags:
      - magic
      - callback
  /flows/magic/login:
    get:
      description: login logs in a user with a Magic Link
      parameters:
      - description: Email Address
        in: query
        name: email
        required: true
        schema:
          type: string
      - description: Next Redirect URL
        in: query
        name: next
        required: true
        schema:
          type: string
      - description: Device Flow Code
        in: query
        name: code
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
        "307":
          description: Temporary Redirect
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                type: string
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: login logs in a user with a Magic Link
      tags:
      - magic
      - login
  /health:
    get:
      description: health returns the health check status
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
        "503":
          content:
            application/json:
              schema:
                type: string
          description: Service Unavailable
      summary: health returns the health check status
      tags:
      - health
  /logout:
    post:
      description: logout logs out a user
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: logout logs out a user
      tags:
      - logout
  /public:
    get:
      description: public returns the current public key and session information
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.PublicResponse'
          description: OK
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                type: string
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      summary: public returns the current public key and session information
      tags:
      - public
servers:
- url: localhost:8080
