basePath: /v1
definitions:
  models.DeviceFlowResponse:
    properties:
      code:
        type: string
      poll:
        type: string
      polling_rate_seconds:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: admin@loopholelabs.io
    name: API Support
  description: Auth API, v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://loopholelabs.io/privacy
  title: Auth API v1
  version: "1.0"
paths:
  /flows/device/login:
    get:
      consumes:
      - application/json
      description: login logs in a user with the Device Code Flow
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.DeviceFlowResponse'
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: login logs in a user with the Device Code Flow
      tags:
      - device
      - login
  /flows/device/poll:
    get:
      consumes:
      - application/json
      description: poll polls the device code flow using the poll code
      parameters:
      - description: poll
        in: query
        name: poll
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "429":
          description: Too Many Requests
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: poll polls the device code flow using the poll code
      tags:
      - device
      - poll
  /flows/device/validate:
    get:
      consumes:
      - application/json
      description: validate validates the code
      parameters:
      - description: code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: validate validates the code
      tags:
      - device
      - validate
  /flows/github/callback:
    get:
      consumes:
      - application/json
      description: callback logs in a user with Github
      parameters:
      - description: Next Redirect URL
        in: query
        name: code
        type: string
      - description: Device Flow Code
        in: query
        name: state
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to Next URL
              type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: callback logs in a user with Github
      tags:
      - github
      - callback
  /flows/github/login:
    get:
      consumes:
      - application/json
      description: login logs in a user with Github
      parameters:
      - description: Next Redirect URL
        in: query
        name: next
        required: true
        type: string
      - description: Device Flow Code
        in: query
        name: code
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to Github
              type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: login logs in a user with Github
      tags:
      - github
      - login
  /flows/google/callback:
    get:
      consumes:
      - application/json
      description: callback logs in a user with Google
      parameters:
      - description: Next Redirect URL
        in: query
        name: code
        type: string
      - description: Device Flow Code
        in: query
        name: state
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to Next URL
              type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: callback logs in a user with Google
      tags:
      - google
      - callback
  /flows/google/login:
    get:
      consumes:
      - application/json
      description: login logs in a user with Google
      parameters:
      - description: Next Redirect URL
        in: query
        name: next
        required: true
        type: string
      - description: Device Flow Code
        in: query
        name: code
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to Google
              type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: login logs in a user with Google
      tags:
      - google
      - login
  /flows/magic/callback:
    get:
      consumes:
      - application/json
      description: callback logs in a user with a Magic Link
      parameters:
      - description: magic link token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Temporary Redirect
          headers:
            Location:
              description: Redirects to Next URL
              type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: callback logs in a user with a Magic Link
      tags:
      - magic
      - callback
  /flows/magic/login:
    get:
      consumes:
      - application/json
      description: login logs in a user with a Magic Link
      parameters:
      - description: Email Address
        in: query
        name: email
        required: true
        type: string
      - description: Next Redirect URL
        in: query
        name: next
        required: true
        type: string
      - description: Device Flow Code
        in: query
        name: code
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "307":
          description: Temporary Redirect
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: login logs in a user with a Magic Link
      tags:
      - magic
      - login
  /health:
    get:
      consumes:
      - application/json
      description: health returns the health check status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "503":
          description: Service Unavailable
          schema:
            type: string
      summary: health returns the health check status
      tags:
      - health
  /logout:
    post:
      consumes:
      - application/json
      description: logout logs out a user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: logout logs out a user
      tags:
      - logout
  /public:
    get:
      consumes:
      - application/json
      description: public returns the current public ket
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: public returns the current public key
      tags:
      - public
schemes:
- https
swagger: "2.0"
