// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeServicekeys holds the string denoting the servicekeys edge name in mutations.
	EdgeServicekeys = "servicekeys"
	// EdgeApikeys holds the string denoting the apikeys edge name in mutations.
	EdgeApikeys = "apikeys"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ServicekeysTable is the table that holds the servicekeys relation/edge.
	ServicekeysTable = "service_keys"
	// ServicekeysInverseTable is the table name for the ServiceKey entity.
	// It exists in this package in order to avoid circular dependency with the "servicekey" package.
	ServicekeysInverseTable = "service_keys"
	// ServicekeysColumn is the table column denoting the servicekeys relation/edge.
	ServicekeysColumn = "user_servicekeys"
	// ApikeysTable is the table that holds the apikeys relation/edge.
	ApikeysTable = "api_keys"
	// ApikeysInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	ApikeysInverseTable = "api_keys"
	// ApikeysColumn is the table column denoting the apikeys relation/edge.
	ApikeysColumn = "user_apikeys"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUsername holds the default value on creation for the "username" field.
	DefaultUsername string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
