// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT identifier, primary_email, default_organization, last_seen, created_at
FROM users
WHERE identifier = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser)
	var i User
	err := row.Scan(
		&i.Identifier,
		&i.PrimaryEmail,
		&i.DefaultOrganization,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}
