/*
	Copyright 2022 Loophole Labs

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		   http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/

// Code generated by ent, DO NOT EDIT.

package githubflow

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/loopholelabs/auth/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldState), v))
	})
}

// Organization applies equality check predicate on the "organization" field. It's identical to OrganizationEQ.
func Organization(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOrganization), v))
	})
}

// Verifier applies equality check predicate on the "verifier" field. It's identical to VerifierEQ.
func Verifier(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVerifier), v))
	})
}

// Challenge applies equality check predicate on the "challenge" field. It's identical to ChallengeEQ.
func Challenge(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldChallenge), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GithubFlow {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GithubFlow {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldState), v))
	})
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldState), v))
	})
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.GithubFlow {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldState), v...))
	})
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.GithubFlow {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldState), v...))
	})
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldState), v))
	})
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldState), v))
	})
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldState), v))
	})
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldState), v))
	})
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldState), v))
	})
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldState), v))
	})
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldState), v))
	})
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldState), v))
	})
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldState), v))
	})
}

// OrganizationEQ applies the EQ predicate on the "organization" field.
func OrganizationEQ(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOrganization), v))
	})
}

// OrganizationNEQ applies the NEQ predicate on the "organization" field.
func OrganizationNEQ(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOrganization), v))
	})
}

// OrganizationIn applies the In predicate on the "organization" field.
func OrganizationIn(vs ...string) predicate.GithubFlow {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldOrganization), v...))
	})
}

// OrganizationNotIn applies the NotIn predicate on the "organization" field.
func OrganizationNotIn(vs ...string) predicate.GithubFlow {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldOrganization), v...))
	})
}

// OrganizationGT applies the GT predicate on the "organization" field.
func OrganizationGT(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldOrganization), v))
	})
}

// OrganizationGTE applies the GTE predicate on the "organization" field.
func OrganizationGTE(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldOrganization), v))
	})
}

// OrganizationLT applies the LT predicate on the "organization" field.
func OrganizationLT(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldOrganization), v))
	})
}

// OrganizationLTE applies the LTE predicate on the "organization" field.
func OrganizationLTE(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldOrganization), v))
	})
}

// OrganizationContains applies the Contains predicate on the "organization" field.
func OrganizationContains(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldOrganization), v))
	})
}

// OrganizationHasPrefix applies the HasPrefix predicate on the "organization" field.
func OrganizationHasPrefix(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldOrganization), v))
	})
}

// OrganizationHasSuffix applies the HasSuffix predicate on the "organization" field.
func OrganizationHasSuffix(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldOrganization), v))
	})
}

// OrganizationEqualFold applies the EqualFold predicate on the "organization" field.
func OrganizationEqualFold(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldOrganization), v))
	})
}

// OrganizationContainsFold applies the ContainsFold predicate on the "organization" field.
func OrganizationContainsFold(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldOrganization), v))
	})
}

// VerifierEQ applies the EQ predicate on the "verifier" field.
func VerifierEQ(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVerifier), v))
	})
}

// VerifierNEQ applies the NEQ predicate on the "verifier" field.
func VerifierNEQ(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldVerifier), v))
	})
}

// VerifierIn applies the In predicate on the "verifier" field.
func VerifierIn(vs ...string) predicate.GithubFlow {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldVerifier), v...))
	})
}

// VerifierNotIn applies the NotIn predicate on the "verifier" field.
func VerifierNotIn(vs ...string) predicate.GithubFlow {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldVerifier), v...))
	})
}

// VerifierGT applies the GT predicate on the "verifier" field.
func VerifierGT(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldVerifier), v))
	})
}

// VerifierGTE applies the GTE predicate on the "verifier" field.
func VerifierGTE(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldVerifier), v))
	})
}

// VerifierLT applies the LT predicate on the "verifier" field.
func VerifierLT(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldVerifier), v))
	})
}

// VerifierLTE applies the LTE predicate on the "verifier" field.
func VerifierLTE(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldVerifier), v))
	})
}

// VerifierContains applies the Contains predicate on the "verifier" field.
func VerifierContains(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldVerifier), v))
	})
}

// VerifierHasPrefix applies the HasPrefix predicate on the "verifier" field.
func VerifierHasPrefix(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldVerifier), v))
	})
}

// VerifierHasSuffix applies the HasSuffix predicate on the "verifier" field.
func VerifierHasSuffix(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldVerifier), v))
	})
}

// VerifierEqualFold applies the EqualFold predicate on the "verifier" field.
func VerifierEqualFold(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldVerifier), v))
	})
}

// VerifierContainsFold applies the ContainsFold predicate on the "verifier" field.
func VerifierContainsFold(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldVerifier), v))
	})
}

// ChallengeEQ applies the EQ predicate on the "challenge" field.
func ChallengeEQ(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldChallenge), v))
	})
}

// ChallengeNEQ applies the NEQ predicate on the "challenge" field.
func ChallengeNEQ(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldChallenge), v))
	})
}

// ChallengeIn applies the In predicate on the "challenge" field.
func ChallengeIn(vs ...string) predicate.GithubFlow {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldChallenge), v...))
	})
}

// ChallengeNotIn applies the NotIn predicate on the "challenge" field.
func ChallengeNotIn(vs ...string) predicate.GithubFlow {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldChallenge), v...))
	})
}

// ChallengeGT applies the GT predicate on the "challenge" field.
func ChallengeGT(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldChallenge), v))
	})
}

// ChallengeGTE applies the GTE predicate on the "challenge" field.
func ChallengeGTE(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldChallenge), v))
	})
}

// ChallengeLT applies the LT predicate on the "challenge" field.
func ChallengeLT(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldChallenge), v))
	})
}

// ChallengeLTE applies the LTE predicate on the "challenge" field.
func ChallengeLTE(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldChallenge), v))
	})
}

// ChallengeContains applies the Contains predicate on the "challenge" field.
func ChallengeContains(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldChallenge), v))
	})
}

// ChallengeHasPrefix applies the HasPrefix predicate on the "challenge" field.
func ChallengeHasPrefix(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldChallenge), v))
	})
}

// ChallengeHasSuffix applies the HasSuffix predicate on the "challenge" field.
func ChallengeHasSuffix(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldChallenge), v))
	})
}

// ChallengeEqualFold applies the EqualFold predicate on the "challenge" field.
func ChallengeEqualFold(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldChallenge), v))
	})
}

// ChallengeContainsFold applies the ContainsFold predicate on the "challenge" field.
func ChallengeContainsFold(v string) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldChallenge), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GithubFlow) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GithubFlow) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GithubFlow) predicate.GithubFlow {
	return predicate.GithubFlow(func(s *sql.Selector) {
		p(s.Not())
	})
}
