/*
	Copyright 2023 Loophole Labs

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		   http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/

// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDeviceCallbackParams creates a new PostDeviceCallbackParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDeviceCallbackParams() *PostDeviceCallbackParams {
	return &PostDeviceCallbackParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDeviceCallbackParamsWithTimeout creates a new PostDeviceCallbackParams object
// with the ability to set a timeout on a request.
func NewPostDeviceCallbackParamsWithTimeout(timeout time.Duration) *PostDeviceCallbackParams {
	return &PostDeviceCallbackParams{
		timeout: timeout,
	}
}

// NewPostDeviceCallbackParamsWithContext creates a new PostDeviceCallbackParams object
// with the ability to set a context for a request.
func NewPostDeviceCallbackParamsWithContext(ctx context.Context) *PostDeviceCallbackParams {
	return &PostDeviceCallbackParams{
		Context: ctx,
	}
}

// NewPostDeviceCallbackParamsWithHTTPClient creates a new PostDeviceCallbackParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDeviceCallbackParamsWithHTTPClient(client *http.Client) *PostDeviceCallbackParams {
	return &PostDeviceCallbackParams{
		HTTPClient: client,
	}
}

/*
PostDeviceCallbackParams contains all the parameters to send to the API endpoint

	for the post device callback operation.

	Typically these are written to a http.Request.
*/
type PostDeviceCallbackParams struct {

	/* Code.

	   device code
	*/
	Code string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post device callback params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDeviceCallbackParams) WithDefaults() *PostDeviceCallbackParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post device callback params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDeviceCallbackParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post device callback params
func (o *PostDeviceCallbackParams) WithTimeout(timeout time.Duration) *PostDeviceCallbackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post device callback params
func (o *PostDeviceCallbackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post device callback params
func (o *PostDeviceCallbackParams) WithContext(ctx context.Context) *PostDeviceCallbackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post device callback params
func (o *PostDeviceCallbackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post device callback params
func (o *PostDeviceCallbackParams) WithHTTPClient(client *http.Client) *PostDeviceCallbackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post device callback params
func (o *PostDeviceCallbackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCode adds the code to the post device callback params
func (o *PostDeviceCallbackParams) WithCode(code string) *PostDeviceCallbackParams {
	o.SetCode(code)
	return o
}

// SetCode adds the code to the post device callback params
func (o *PostDeviceCallbackParams) SetCode(code string) {
	o.Code = code
}

// WriteToRequest writes these params to a swagger request
func (o *PostDeviceCallbackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param code
	qrCode := o.Code
	qCode := qrCode
	if qCode != "" {

		if err := r.SetQueryParam("code", qCode); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
