name: Build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true

      - name: Install swaggo
        run: go install github.com/swaggo/swag/cmd/swag@v1.8.10

      - name: Install swagger
        run: go install github.com/go-swagger/go-swagger/cmd/swagger@v0.30.4

      - name: Generate
        run: go generate ./...

      - name: Build
        run: go build -v ./...
